apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow-app
  template:
    metadata:
      labels:
        app: wisecow-app
    spec:
      containers:
        - name: wisecow-app
          image: nirmala15/new_wisecow_app:latest  # Your Docker image
          ports:
            - containerPort: 5000
