apiVersion: v1
kind: Service
metadata:
  name: wisecow-app-service
spec:
  selector:
    app: wisecow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001  # Add this line for NodePort
  type: NodePort  # Change to NodePort for local environments
