name: CI/CD Workflow for Wisecow App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.nirmala15 }}
        password: ${{ secrets.Nirmala@9703 }} 

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t nirmala15/new_wisecow_app:latest .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push nirmala15/new_wisecow_app:latest

    # Step 6: Set up kubectl for Kubernetes deployment
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 7: Configure kubectl for deployment
    - name: Configure kubectl with KUBECONFIG
      run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    # Step 8: Apply Kubernetes deployment
    - name: Apply Kubernetes deployment
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/ingress.yaml

    # Step 9: Confirm deployment success
    - name: Check Kubernetes pods status
      run: kubectl get pods
